# -*- coding: utf-8 -*-
"""
utils.py
--------
Shared utility functions for the fear conditioning behavioral analysis pipeline.
Do not edit this file unless you know what you're doing — user configuration
belongs in runner.py.
"""

import re
import string
from pathlib import Path
from typing import Optional, List

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.textpath import TextPath
from matplotlib.transforms import Affine2D


# =============================================================================
# Column normalization
# =============================================================================

def norm_colname(c: str) -> str:
    c = str(c).strip().lower()
    c = c.replace("\u00a0", " ")
    c = re.sub(r"\s+", " ", c)
    c = c.replace("(", "").replace(")", "")
    c = c.replace("+", "plus").replace("-", "minus")
    c = c.replace("/", " ").replace("\\", " ")
    c = c.replace(" ", "_")
    return c


def load_csv(path: Path) -> pd.DataFrame:
    try:
        df = pd.read_csv(path, engine="python")
    except Exception:
        df = pd.read_csv(path, sep=None, engine="python")
    return df.rename(columns={c: norm_colname(c) for c in df.columns})


# =============================================================================
# Treatment label normalization
# =============================================================================

def build_treatment_normalizer(alias_map: dict) -> dict:
    lookup = {}
    for canonical, aliases in alias_map.items():
        for alias in aliases:
            lookup[alias.strip().lower()] = canonical
    return lookup


def normalize_treatment(value, lookup: dict) -> str:
    if pd.isna(value):
        return "Unknown"
    return lookup.get(str(value).strip().lower(), str(value).strip())


# =============================================================================
# Sex normalization
# =============================================================================

def normalize_sex(x) -> str:
    if pd.isna(x):
        return "Unknown"
    s = str(x).strip().lower()
    if s.startswith("m"):
        return "M"
    if s.startswith("f"):
        return "F"
    return "Unknown"


# =============================================================================
# Folder parsing
# =============================================================================

def parse_folder_bits(folder_name: str) -> tuple:
    s = folder_name.strip()
    m = re.match(r"^(d\d{2})_(context[ab])_(.+)$", s, flags=re.IGNORECASE)
    if m:
        return m.group(1).lower(), m.group(2), m.group(3)
    m = re.match(r"^Day\s+(\d+)\s+(.+)$", s, flags=re.IGNORECASE)
    if m:
        day  = f"d{int(m.group(1)):02d}"
        rest = m.group(2).strip()
        if "_" in rest:
            maybe_ctx, maybe_sess = rest.rsplit("_", 1)
            if maybe_sess.isdigit():
                return day, maybe_ctx, maybe_sess
        return day, rest, None
    return folder_name, None, None


def day_sort_key(folder_name: str) -> tuple:
    m = re.match(r"^d(\d{2})_", folder_name, flags=re.IGNORECASE)
    if m:
        return (int(m.group(1)), folder_name.lower())
    return (999, folder_name.lower())


def find_session_dirs(behaviordata: Path, pattern: str = r"^d\d{2}_") -> list:
    dirs = [
        p for p in behaviordata.iterdir()
        if p.is_dir() and re.search(pattern, p.name, flags=re.IGNORECASE)
    ]
    return sorted(dirs, key=lambda p: day_sort_key(p.name))


# =============================================================================
# Metadata loading — supports multiple BehaviorData directories
# =============================================================================

def load_metadata(behaviordata: Path) -> Optional[pd.DataFrame]:
    """
    Load animals_metadata.xlsx from a single BehaviorData directory.
    Returns a normalized DataFrame or None if not found.
    If cohort_id is absent, it is synthesized from the folder name.
    """
    meta_path = behaviordata / "animals_metadata.xlsx"
    if not meta_path.exists():
        print(f"[warn] Missing {meta_path}; metadata-dependent features will be skipped.")
        return None

    meta = pd.read_excel(meta_path)
    meta.columns = [norm_colname(c) for c in meta.columns]

    if "behavior_id" not in meta.columns:
        print("[warn] 'behavior_id' column not found in animals_metadata.xlsx.")
        return None

    # Synthesize cohort_id from folder name if not provided
    if "cohort_id" not in meta.columns:
        meta["cohort_id"] = behaviordata.name
        print(f"[info] No cohort_id column found in {meta_path.name}; "
              f"using folder name '{behaviordata.name}' as cohort_id.")

    meta["behavior_id"] = meta["behavior_id"].apply(_normalize_key)
    meta = meta[meta["behavior_id"] != ""].copy()
    return meta


def load_metadata_multi(behaviordata_dirs: List[Path]) -> Optional[pd.DataFrame]:
    """
    Load and merge animals_metadata.xlsx from multiple BehaviorData directories.
    Each directory's metadata is tagged with its cohort_id (from the column if
    present, otherwise synthesized from the folder name).
    Returns a single merged DataFrame, or None if no metadata was found.
    """
    frames = []
    for bd in behaviordata_dirs:
        meta = load_metadata(bd)
        if meta is not None:
            # Tag each row with the source BehaviorData path so analysis
            # scripts can route per-session outputs to the right folder.
            meta["_behaviordata"] = str(bd)
            frames.append(meta)

    if not frames:
        return None

    merged = pd.concat(frames, ignore_index=True)

    # Warn on duplicate behavior_ids across cohorts (allowed but worth flagging)
    dupes = merged[merged.duplicated(subset=["behavior_id"], keep=False)]
    if not dupes.empty:
        ids = dupes["behavior_id"].unique().tolist()
        print(f"[warn] behavior_id values appear in more than one cohort's "
              f"metadata — ensure they are distinct or results may be mixed up: "
              f"{ids}")

    return merged


# =============================================================================
# Internal helpers
# =============================================================================

def _normalize_key(v) -> str:
    if pd.isna(v):
        return ""
    return str(v).strip().upper()


def normalize_behavior_id_for_lookup(bid: str) -> Optional[str]:
    if bid is None:
        return None
    s = str(bid).strip().lower()
    s = s.strip("()[]{}\"'")
    s = re.sub(r"(_\d+(_fixed)?|_fixed)$", "", s, flags=re.IGNORECASE)
    s = s.strip(string.whitespace + string.punctuation.replace("-", "").replace("_", ""))
    return s


def extract_behavior_id_token(text: str) -> Optional[str]:
    if text is None:
        return None
    s = str(text).strip().strip("()[]{}\"'").lstrip("_- ")
    s = re.split(r"[_\s\(\)\[\]\{\}]+", s, maxsplit=1)[0].strip()
    if not s:
        return None
    for pat in [r"^([0-9]+[A-Za-z]?(?:-[0-9A-Za-z]+)?)",
                r"^([A-Za-z]?[0-9]+[A-Za-z]?(?:-[0-9A-Za-z]+)?)"]:
        m = re.match(pat, s)
        if m:
            return m.group(1)
    return s


def _metadata_behavior_id_from_text(text: str, meta_df: Optional[pd.DataFrame]) -> Optional[str]:
    if text is None or meta_df is None or "behavior_id" not in meta_df.columns:
        return None

    hay = str(text)
    hay_lower = hay.lower()
    matches = []

    for bid in meta_df["behavior_id"].dropna().astype(str).unique().tolist():
        norm = normalize_behavior_id_for_lookup(bid)
        if not norm:
            continue
        clean = re.sub(r"[^a-z0-9]", "", norm)
        if not clean:
            continue
        if len(clean) < 3:
            continue

        tokens = re.findall(r"[a-z0-9]+", norm)
        if not tokens:
            continue

        # Allow junk before the ID and minor punctuation differences inside the
        # ID, but require a clean ending boundary. This prevents a metadata ID
        # like "6069-b" from matching inside a longer filename token such as
        # "sdf6069-b-cobalt_...".
        body = r"[^a-z0-9]*".join(re.escape(t) for t in tokens)
        pat = re.compile(body + r"(?=$|[_\s\(\)\[\]\{\}]|[^a-z0-9-])")
        m = pat.search(hay_lower)
        if m:
            found = hay[m.start():m.end()]
            matches.append((len(clean), m.start(), found))

    if not matches:
        return None

    # Prefer the most specific metadata ID. This avoids returning "6069" when
    # "6069-bugtester" is also present in metadata.
    matches.sort(key=lambda x: (-x[0], x[1]))
    return matches[0][2]


def parse_filename_bits(csv_path: Path, meta_df: Optional[pd.DataFrame] = None) -> tuple:
    stem = csv_path.stem
    m    = re.search(r"(\d{2}-\d{2}-\d{2})", stem)
    if not m:
        return None, None
    date = m.group(1)
    rest = stem[m.end():].lstrip("_ -")
    if not rest:
        return date, None
    bid = extract_behavior_id_token(rest)
    if meta_df is not None:
        if bid and not find_metadata_for_behavior(meta_df, bid).empty:
            return date, bid
        meta_bid = _metadata_behavior_id_from_text(rest, meta_df)
        if meta_bid:
            return date, meta_bid
    return date, bid


def find_metadata_for_behavior(meta_df: pd.DataFrame, raw_bid: str) -> pd.DataFrame:
    if raw_bid is None or meta_df is None:
        return pd.DataFrame()

    bid_raw = str(raw_bid)
    if "_" in bid_raw:
        bid_raw = bid_raw.split("_", 1)[0]

    bid_norm = normalize_behavior_id_for_lookup(bid_raw)
    if not bid_norm:
        return pd.DataFrame()

    meta_beh   = meta_df["behavior_id"].astype(str)
    meta_norm  = meta_beh.str.lower().str.strip()
    meta_clean = meta_norm.str.replace(r"[^a-z0-9]", "", regex=True)

    mask = meta_norm == bid_norm
    if mask.any():
        return meta_df[mask]

    cleaned = re.sub(r"[^a-z0-9]", "", bid_norm)
    if cleaned:
        mask = meta_clean == cleaned
        if mask.any():
            return meta_df[mask]

    m = re.match(r"(.+?)(-\d+|-[a-z0-9]+)$", bid_norm)
    if m:
        mask = meta_norm == m.group(1)
        if mask.any():
            return meta_df[mask]

    mnum = re.match(r"^0*([0-9]+)([a-z])?$", bid_norm)
    if mnum:
        num, letter = mnum.group(1), (mnum.group(2) or "").lower()
        for suffix in ([f"-{num}", num] + ([f"{num}{letter}", ] if letter else [])):
            mask = meta_norm.str.endswith(suffix)
            if mask.any():
                return meta_df[mask]
        if letter:
            mask = meta_clean.str.endswith(f"{num}{letter}")
            if mask.any():
                return meta_df[mask]

    pat  = re.compile(r"(^|[-_])" + re.escape(bid_norm) + r"($|[-_])")
    mask = meta_norm.apply(lambda s: bool(pat.search(s)))
    if mask.any():
        return meta_df[mask]

    if cleaned:
        for fn in [meta_clean.str.startswith, meta_clean.str.endswith]:
            mask = fn(cleaned)
            if mask.any():
                return meta_df[mask]

    return pd.DataFrame()


# =============================================================================
# Trial detection
# =============================================================================

def normalize_trial_type(v: str) -> str:
    if not isinstance(v, str):
        return "unknown"
    s = v.strip().lower().replace("_", "")
    if s in {"cs+", "csplus", "csplus1", "csp"}:
        return "CS+"
    if s in {"cs-", "csminus", "csminus1", "csm"}:
        return "CS-"
    if s in {"iti", "intertrialinterval", "inter_trial_interval"}:
        return "ITI"
    return "unknown"


def rising_edges(series: pd.Series) -> np.ndarray:
    s    = series.fillna(0).astype(float)
    prev = s.shift(1, fill_value=0)
    return ((prev <= 0) & (s > 0)).to_numpy().nonzero()[0]


def get_off_time(df: pd.DataFrame, time_col: str, off_col: Optional[str],
                 start_time: float, default_len: float) -> float:
    if off_col is None or off_col not in df.columns:
        return start_time + default_len
    sub = df[df[time_col] >= start_time]
    idx = sub[off_col].fillna(0).astype(float).to_numpy().nonzero()[0]
    if len(idx) == 0:
        return start_time + default_len
    return float(df.loc[sub.index[idx[0]], time_col])


def clip_interval(start: float, end: float, t_min: float, t_max: float) -> tuple:
    return max(start, t_min), min(end, t_max)


def detect_trials_from_ttl(df, time_col, csplus_on, csplus_off,
                            csminus_on, csminus_off,
                            trial_len_s=30.0, iti_len_s=60.0) -> tuple:
    t = df[time_col].astype(float).to_numpy()
    t_min, t_max = float(np.nanmin(t)), float(np.nanmax(t))
    trials = []

    for on_col, off_col, label in [
        (csplus_on, csplus_off, "CS+"),
        (csminus_on, csminus_off, "CS-"),
    ]:
        if on_col and on_col in df.columns:
            for ix in rising_edges(df[on_col]):
                start = float(df.iloc[ix][time_col])
                end   = get_off_time(df, time_col, off_col, start, trial_len_s)
                start, end = clip_interval(start, end, t_min, t_max)
                if end > start:
                    trials.append(dict(type=label, start=start, end=end))

    trials.sort(key=lambda d: d["start"])

    itis = []
    for tr in trials:
        s, e = clip_interval(tr["end"], tr["end"] + iti_len_s, t_min, t_max)
        if e > s:
            itis.append(dict(type="ITI", start=s, end=e))

    counts = {"CS+": 0, "CS-": 0, "ITI": 0}
    for w in trials + itis:
        counts[w["type"]] += 1
        w["trial_index"] = counts[w["type"]]

    return trials, itis


def detect_trials_from_tone_status(df, time_col, csplus_col, csminus_col,
                                    iti_len_s=60.0) -> tuple:
    t = df[time_col].astype(float).to_numpy()
    t_min, t_max = float(np.nanmin(t)), float(np.nanmax(t))
    trials = []

    for col, label in [(csplus_col, "CS+"), (csminus_col, "CS-")]:
        s    = df[col].fillna(0).astype(float).to_numpy()
        prev = np.roll(s, 1); prev[0] = 0
        starts = np.where((prev <= 0) & (s > 0))[0]
        ends   = np.where((prev > 0) & (s <= 0))[0]
        if len(starts) > len(ends):
            ends = np.append(ends, len(s) - 1)
        for i, si in enumerate(starts):
            if i >= len(ends):
                break
            st, en = clip_interval(float(t[si]), float(t[ends[i]]), t_min, t_max)
            if en > st:
                trials.append(dict(type=label, start=st, end=en))

    trials.sort(key=lambda d: d["start"])

    itis = []
    for tr in trials:
        s, e = clip_interval(tr["end"], tr["end"] + iti_len_s, t_min, t_max)
        if e > s:
            itis.append(dict(type="ITI", start=s, end=e))

    counts = {"CS+": 0, "CS-": 0, "ITI": 0}
    for w in trials + itis:
        counts[w["type"]] += 1
        w["trial_index"] = counts[w["type"]]

    return trials, itis


def detect_trials(df: pd.DataFrame, time_col: str, cfg: dict) -> tuple:
    mode            = cfg.get("cs_detection_mode", "auto")
    csplus_pattern  = cfg.get("tone_status_col_csplus",  "cs plus tone status")
    csminus_pattern = cfg.get("tone_status_col_csminus", "cs minus tone status")

    def _try_tone_status():
        csplus_col, csminus_col = find_tone_status_cols(df, csplus_pattern, csminus_pattern, cfg)
        trials, itis = detect_trials_from_tone_status(df, time_col, csplus_col, csminus_col)
        return trials, itis, f"tone_status ({csplus_col}, {csminus_col})"

    def _try_ttl():
        csplus_on, csplus_off, csminus_on, csminus_off = find_ttl_cols(df, cfg)
        trials, itis = detect_trials_from_ttl(
            df, time_col, csplus_on, csplus_off, csminus_on, csminus_off)
        return trials, itis, f"TTL ({csplus_on}, {csminus_on})"

    if mode == "tone_status":
        return _try_tone_status()
    if mode == "ttl":
        return _try_ttl()
    try:
        return _try_tone_status()
    except ValueError:
        return _try_ttl()


def filter_trials(df: pd.DataFrame, cs_cap: int = 10, iti_cap: int = 20) -> pd.DataFrame:
    if "_trial_type" not in df.columns and "trial_type" in df.columns:
        df = df.copy()
        df["_trial_type"] = df["trial_type"]

    if "trial_index" not in df.columns:
        df = df.sort_values(["_day_folder", "treatment_group", "_trial_type", "_source_csv"])
        df["trial_index"] = (
            df.groupby(["_day_folder", "treatment_group", "_trial_type", "_source_csv"])
              .cumcount() + 1
        )

    capped = []
    for label, sub in df.groupby("_trial_type", dropna=False):
        if label in ("CS+", "CS-"):
            capped.append(sub[sub["trial_index"] <= cs_cap])
        elif label == "ITI":
            capped.append(sub[sub["trial_index"] <= iti_cap])
        else:
            capped.append(sub)
    return pd.concat(capped, ignore_index=True) if capped else df


# =============================================================================
# Signal integration
# =============================================================================

def integrate_binary(t, x, start, end) -> float:
    t = np.asarray(t, dtype=float)
    x = np.asarray(x, dtype=float)
    if len(t) < 2 or end <= start:
        return 0.0
    dt      = np.diff(t)
    dt      = np.append(dt, dt[-1])
    left    = np.maximum(t, start)
    right   = np.minimum(t + dt, end)
    overlap = np.maximum(0.0, right - left)
    return float((overlap * (x > 0).astype(float)).sum())


def interval_fraction_on(t, x, start, end) -> float:
    denom = integrate_binary(t, np.ones_like(x), start, end)
    if denom < 1e-12:
        return 0.0
    return integrate_binary(t, x, start, end) / denom


# =============================================================================
# Column finders
# =============================================================================

def _cfg_column_aliases(cfg: Optional[dict]) -> dict:
    if not cfg:
        return {}
    aliases = cfg.get("column_aliases", {})
    return aliases if isinstance(aliases, dict) else {}


def _column_match_mode(cfg: Optional[dict]) -> str:
    if not cfg:
        return "fallback"
    mode = str(cfg.get("column_match_mode", "fallback")).strip().lower()
    if mode not in {"strict", "fallback"}:
        raise ValueError(
            f"Unknown COLUMN_MATCH_MODE '{mode}'. Use 'strict' or 'fallback'."
        )
    return mode


def _format_match_list(cols: list) -> str:
    return ", ".join(repr(c) for c in cols)


def _one_column_or_raise(role: str, matches: list) -> Optional[str]:
    if len(matches) == 1:
        return matches[0]
    if len(matches) > 1:
        raise ValueError(
            f"Ambiguous column match for '{role}': matched "
            f"{_format_match_list(matches)}. Update COLUMN_ALIASES['{role}'] "
            "in runner.py so only one column matches."
        )
    return None


def _alias_matches(df: pd.DataFrame, role: str, cfg: Optional[dict]) -> list:
    aliases = _cfg_column_aliases(cfg).get(role, [])
    if isinstance(aliases, str):
        aliases = [aliases]
    norm_aliases = {
        norm_colname(alias)
        for alias in aliases
        if alias is not None and str(alias).strip()
    }
    if not norm_aliases:
        return []
    return [c for c in df.columns.tolist() if norm_colname(c) in norm_aliases]


def resolve_column(df: pd.DataFrame, role: str, cfg: Optional[dict] = None,
                   fallback=None, required: bool = True) -> Optional[str]:
    """
    Resolve one normalized dataframe column for a semantic role.

    Matching order:
      1. Exact normalized aliases from cfg["column_aliases"][role].
      2. In fallback mode only, the role's older heuristic matcher.

    More than one match is always an error; the pipeline should not guess which
    signal to analyze.
    """
    alias_match = _one_column_or_raise(role, _alias_matches(df, role, cfg))
    if alias_match is not None:
        return alias_match

    mode = _column_match_mode(cfg)
    if mode == "fallback" and fallback is not None:
        fallback_match = _one_column_or_raise(role, fallback(df.columns.tolist()))
        if fallback_match is not None:
            return fallback_match

    if required:
        aliases = _cfg_column_aliases(cfg).get(role, [])
        alias_msg = f" Aliases checked: {aliases}." if aliases else ""
        raise ValueError(
            f"No column found for '{role}' in {mode} column match mode."
            f"{alias_msg} Columns present: {df.columns.tolist()}"
        )
    return None


def find_time_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> str:
    return resolve_column(
        df, "time", cfg,
        fallback=lambda cols: [c for c in cols if c.startswith("time")]
    )


def find_freeze_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> str:
    return resolve_column(
        df, "freezing", cfg,
        fallback=lambda cols: [c for c in cols if "freez" in c]
    )


def find_platform_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> str:
    return resolve_column(
        df, "in_platform", cfg,
        fallback=lambda cols: [c for c in cols if c == "in_platform"]
    )


def find_speed_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> str:
    return resolve_column(
        df, "speed", cfg,
        fallback=lambda cols: [c for c in cols if c == "speed" or "speed" in c]
    )


def find_ttl_cols(df: pd.DataFrame, cfg: Optional[dict] = None) -> tuple:
    cols = df.columns.tolist()

    def like(words):
        pat     = re.compile(r".*".join(re.escape(w) for w in words))
        matches = [c for c in cols if pat.search(c)]
        return matches

    csplus_on = resolve_column(
        df, "csplus_on", cfg, required=False,
        fallback=lambda _: like(["cs", "plus", "on", "activat"]) or like(["csplus", "on"]) or like(["cs", "plus", "on"])
    )
    csplus_off = resolve_column(
        df, "csplus_off", cfg, required=False,
        fallback=lambda _: like(["cs", "plus", "off", "activat"]) or like(["csplus", "off"]) or like(["cs", "plus", "off"])
    )
    csminus_on = resolve_column(
        df, "csminus_on", cfg, required=False,
        fallback=lambda _: like(["cs", "minus", "on", "activat"]) or like(["csminus", "on"]) or like(["cs", "minus", "on"])
    )
    csminus_off = resolve_column(
        df, "csminus_off", cfg, required=False,
        fallback=lambda _: like(["cs", "minus", "off", "activat"]) or like(["csminus", "off"]) or like(["cs", "minus", "off"])
    )
    return csplus_on, csplus_off, csminus_on, csminus_off


def find_tone_status_cols(df: pd.DataFrame,
                          csplus_pattern:  str = "cs plus tone status",
                          csminus_pattern: str = "cs minus tone status",
                          cfg: Optional[dict] = None) -> tuple:
    cols = df.columns.tolist()

    def find_one(pattern: str) -> list:
        norm    = norm_colname(pattern)
        matches = [c for c in cols if norm in c]
        if matches:
            return matches
        tokens  = norm.split("_")
        matches = [c for c in cols if all(t in c for t in tokens)]
        return matches

    csplus = resolve_column(
        df, "csplus_tone_status", cfg,
        fallback=lambda _: find_one(csplus_pattern),
        required=False,
    )
    csminus = resolve_column(
        df, "csminus_tone_status", cfg,
        fallback=lambda _: find_one(csminus_pattern),
        required=False,
    )

    if csplus is None or csminus is None:
        missing = []
        if csplus  is None: missing.append(f"CS+ (pattern: '{csplus_pattern}')")
        if csminus is None: missing.append(f"CS- (pattern: '{csminus_pattern}')")
        raise ValueError(
            f"Tone-status columns not found: {', '.join(missing)}. "
            f"Check TONE_STATUS_COL_CSPLUS / TONE_STATUS_COL_CSMINUS in runner.py."
        )
    return csplus, csminus


def find_latency_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> Optional[str]:
    candidates = ["latency_to_platform_s", "latency_to_platform",
                  "latency_s", "latency", "latency_to_platform__s"]

    def fallback(cols):
        exact = [c for c in candidates if c in cols]
        if exact:
            return exact
        both = [c for c in cols if "latency" in c.lower() and "platform" in c.lower()]
        if both:
            return both
        return [c for c in cols if c.lower().startswith("latency")]

    return resolve_column(
        df, "latency_to_platform", cfg,
        fallback=fallback,
        required=False,
    )


def find_us_cols(df: pd.DataFrame, cfg: Optional[dict] = None) -> tuple:
    cols = df.columns.tolist()

    def like(words):
        matches = []
        for c in cols:
            tokens = re.split(r"[^a-z0-9]+", c.lower())
            pos = 0
            ok = True
            for word in words:
                while pos < len(tokens) and not tokens[pos].startswith(word):
                    pos += 1
                if pos >= len(tokens):
                    ok = False
                    break
                pos += 1
            if ok:
                matches.append(c)
        return matches

    us_on = resolve_column(
        df, "us_on", cfg, required=False,
        fallback=lambda _: like(["us", "on", "activat"]) or like(["shock", "on", "activat"]) or like(["us", "on"]) or like(["shock", "on"])
    )
    us_off = resolve_column(
        df, "us_off", cfg, required=False,
        fallback=lambda _: like(["us", "off", "activat"]) or like(["shock", "off", "activat"]) or like(["us", "off"]) or like(["shock", "off"])
    )
    return us_on, us_off


def find_shocker_col(df: pd.DataFrame, cfg: Optional[dict] = None) -> Optional[str]:
    return resolve_column(
        df, "shocker_active", cfg,
        fallback=lambda cols: [c for c in cols if "shocker" in c.lower() and "active" in c.lower()],
        required=False,
    )


# =============================================================================
# Plotting helpers
# =============================================================================

def make_sex_markers() -> dict:
    def _marker(char):
        tp = TextPath((0, 0), char, size=1.0, prop=dict(family="DejaVu Sans"))
        bb = tp.get_extents()
        cx, cy = (bb.x0 + bb.x1) / 2.0, (bb.y0 + bb.y1) / 2.0
        return Affine2D().translate(-cx, -cy).transform_path(tp)
    return {"M": _marker("♂"), "F": _marker("♀"), "Unknown": None}


SEX_MARKERS = make_sex_markers()


def sparse_xticks(ax: plt.Axes, last_trial: int, every: int = 3):
    ticks = range(1, last_trial + 1)
    ax.set_xticks(ticks)
    ax.set_xticklabels(
        [str(t) if (t - 1) % every == 0 else "" for t in ticks], fontsize=8
    )


def build_sex_color_map(treatment_color_map: dict) -> dict:
    import matplotlib.colors as mcolors
    sex_map = {}
    for trt, base_hex in treatment_color_map.items():
        base    = mcolors.to_rgb(base_hex)
        female  = tuple(min(1.0, c + (1.0 - c) * 0.5) for c in base)
        unknown = tuple(min(1.0, c + (1.0 - c) * 0.7) for c in base)
        sex_map[(trt, "M")]       = base_hex
        sex_map[(trt, "F")]       = mcolors.to_hex(female)
        sex_map[(trt, "Unknown")] = mcolors.to_hex(unknown)
    return sex_map


def plot_mean_sem(ax: plt.Axes, agg: pd.DataFrame, color=None,
                  label: str = None, marker=None, linestyle: str = "-"):
    if agg.empty:
        return
    if (agg["count"] > 1).any():
        agg = agg.copy()
        agg["sem"] = agg["std"] / agg["count"].pow(0.5)
        ax.fill_between(
            agg["trial_index"],
            agg["mean"] - agg["sem"],
            agg["mean"] + agg["sem"],
            alpha=0.18, linewidth=0, color=color,
        )
    mk = marker if marker is not None else "o" if linestyle != "-" else None
    ax.plot(
        agg["trial_index"], agg["mean"],
        linewidth=2.0, color=color, label=label,
        linestyle=linestyle,
        marker=mk, markersize=7 if mk else 0, markeredgewidth=0.6,
    )


def save_fig(fig: plt.Figure, out_path: Path):
    fig.savefig(out_path, format="svg", bbox_inches="tight")
    plt.close(fig)
    print(f"[ok] Saved: {out_path}")
